local locale = GetLocale()
if locale ~= "enUS" then return end

local _, class = UnitClass("player")
if class ~= "HUNTER" then return end

local _, ns = ...
ns.PET_ABILITIES = {
	["Hyena"] = "Cackling Howl",
	["Monkey"] = "Bad Manner",
	["Tallstrider"] = "Dust Cloud",
	["Warp Stalker"] = "Time Warp",
	["Chimaera"] = "Froststorm Breath",
	["Sporebat"] = "Spore Cloud",
	["Serpent"] = "Serpent's Swiftness",
	["Crocolisk"] = "Ankle Crack",
	["Shale Spider"] = "Embrace of the Shale Spider",
	["Crab"] = "Pin",
	["Turtle"] = "Shell Shield",
	["Dragonhawk"] = "Fire Breath",
	["Porcupine"] = "Paralyzing Quill",
	["Fox"] = "Tailspin",
	["Cat"] = "Roar of Courage",
	["Bat"] = "Sonic Blast",
	["Core Hound"] = "Ancient Hysteria",
	["Raptor"] = "Tear Armor",
	["Carrion Bird"] = "Demoralizing Screech",
	["Direhorn"] = "Reflective Armor Plating",
	["Ravager"] = "Ravage",
	["Wolf"] = "Furious Howl",
	["Devilsaur"] = "Monstrous Bite",
	["Worm"] = "Burrow Attack",
	["Nether Ray"] = "Nether Shock",
	["Basilisk"] = "Petrifying Gaze",
	["Goat"] = "Trample",
	["Quilen"] = "Eternal Guardian",
	["Beetle"] = "Harden Carapace",
	["Moth"] = "Serenity Dust",
	["Water Strider"] = "Still Water",
	["Wasp"] = "Sting",
	["Bear"] = "Demoralizing Roar",
	["Dog"] = "Lock Jaw",
	["Silithid"] = "Qiraji Fortitude",
	["Spirit Beast"] = "Spirit Mend",
	["Boar"] = "Gore",
	["Rhino"] = "Horn Toss",
	["Wind Serpent"] = "Lightning Breath",
	["Crane"] = "Lullaby",
	["Spider"] = "Web",
	["Scorpid"] = "Clench",
	["Gorilla"] = "Pummel",
	["Bird of Prey"] = "Snatch"
}